=== gem15/notification/src/main/resources/xml/severtrans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:st="http://www.severtrans.com" targetNamespace="http://www.severtrans.com" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <!--           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0">-->
    <xs:annotation>
        <xs:documentation>Схема severtrans</xs:documentation>
    </xs:annotation>

    <xs:element name="Shell" type="st:Shell" xmlns="http://www.severtrans.com">
        <xs:annotation>
            <xs:documentation>Контейнер для всех сообщений</xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:complexType name="Shell">
        <xs:sequence minOccurs="0" maxOccurs="1">
            <!-- Общие элементы для всех сообщений -->
            <xs:element name="customerID" type="xs:int" minOccurs="1">
                <xs:annotation>
                    <xs:documentation>ВН ()внутренний номер)</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="msgID" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Уникальный ID каждого сообщения</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="msgType" type="xs:int" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                        Тип сообщений
                        1	Заказ на поставку (УП)
                        2	Заказ на отгрузку (РО)
                        3	Подтверждение завершения поставки
                        4	Подтверждение завершения отгрузки
                        5	Справочник SKU
                        6	Запрос остатков Part Stock
                        7	Подтверждение груз собран
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <!--  -->
            <xs:element name="confirmation" type="st:Confirmation" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Подтверждение приёмки входного сообщения и статус последнего. В случае налии ошибки содержит текст</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="notification" type="st:Notification" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Подтверждение заказов на поставку/отгрузку</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="skuList" type="st:ListSKU" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Обновление товарного справочника (артикулов) SKU</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="partStockRq" type="st:PartStockRq" minOccurs="0" />
            <xs:element name="partStockRs" type="st:PartStockRs" minOccurs="0" />
            <xs:element name="order" type="st:Order" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="Order">
        <xs:annotation>
            <xs:documentation>Заказ на поставку/отгрузку</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="guid" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Уникальный ID заказа для связки с ответными сообщениями</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="action" type="xs:int" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                    Редактирование документа. Необязательный тег
                    0 - новый заказ
                    1 - отмена заказа
                    2 - изменение заказа
                </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="orderType" type="xs:boolean">
                <xs:annotation>
                    <xs:documentation>
                        Тип заказа
                        false (0) - поставка 4101
                        true (1) - отгрузка 4103
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="orderKind" type="xs:string" minOccurs="0" >
                <xs:annotation>
                    <xs:documentation>Справочник Типы заказов  в СОХ</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="orderNo" type="xs:string" >
                <xs:annotation>
                    <xs:documentation>Номер заказа</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="orderDate" type="xs:dateTime" >
                <xs:annotation>
                    <xs:documentation>Дата заказа</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="plannedDate" type="xs:dateTime" >
                <xs:annotation>
                    <xs:documentation>Планируемая (поставки/отгрузки) дата/время заказа</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="contrCode" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>код контрагента</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="contrName" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>наименование контрагента</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="contrAddress" type="xs:string" minOccurs="0" >
                <xs:annotation>
                    <xs:documentation>Адрес контрагента</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="licencePlate" type="xs:string" minOccurs="0" >
                <xs:annotation>
                    <xs:documentation>Регистрационный номер автотраспорта</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="driver" type="xs:string" minOccurs="0" >
                <xs:annotation>
                    <xs:documentation>Водитель</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="comment" type="xs:string" minOccurs="0" >
                <xs:annotation>
                    <xs:documentation>Комментарий к заказу</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="orderLine" type="st:OrderLine" minOccurs="1" maxOccurs="unbounded" >
                <xs:annotation>
                    <xs:documentation>Список товаров заказа</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="OrderLine">
        <xs:sequence>
            <xs:element name="lineNumber" type="xs:int" />
            <xs:element name="article" type="xs:string" />
            <xs:element name="name" type="xs:string" />
            <xs:element name="qty" type="xs:decimal" />
            <xs:element name="storageLife" type="xs:date" minOccurs="0" />
            <xs:element name="category" type="xs:string" minOccurs="0" />
            <xs:element name="mark" type="xs:string" minOccurs="0" />
            <xs:element name="mark2" type="xs:string" minOccurs="0" />
            <xs:element name="mark3" type="xs:string" minOccurs="0" />
            <xs:element name="lot" type="xs:string" minOccurs="0" /> <!-- При указании отгрузка происходит по тем номерам ГТД или вет. справках, какие были указаны -->
            <xs:element name="comment" type="xs:string" minOccurs="0" />
            <!--         <ExpirationDate></ExpirationDate> -дата окончания срока годности
        <ProductionDate>29012020</ProductionDate> - дата производства
           -->
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SKU">
        <xs:annotation>
            <xs:documentation>Номенклатура</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="article" type="xs:string" />
            <xs:element name="name" type="xs:string" />
            <xs:element name="upc" type="xs:string" minOccurs="0" />
            <xs:element name="uofm" type="xs:string" minOccurs="0" />
            <xs:element name="storageLife" type="xs:int" minOccurs="0" />
            <xs:element name="storageCondition" type="xs:string" minOccurs="0" />
            <xs:element name="billingClass" type="xs:string" minOccurs="0" />
            <xs:element name="division" type="xs:string" minOccurs="0" />
            <xs:element name="weight" type="xs:decimal" minOccurs="0" />
            <xs:element name="phvolume" type="xs:decimal" minOccurs="0" />
            <xs:element name="upcList" type="st:upcList" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ListSKU">
        <xs:annotation>
            <xs:documentation>Список номенклатуры</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="sku" type="st:SKU" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PartStockRq">
        <xs:annotation>
            <xs:documentation>Запрос текущих остатков</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="ts" type="xs:dateTime" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PartStockRs">
        <xs:annotation>
            <xs:documentation>Ответ на запрос текущих остатков</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="ts" type="xs:dateTime" />
            <xs:element name="line" type="st:PartStockLine" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PartStockLine">
        <xs:annotation>
            <xs:documentation>Артикул</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="lineNumber" type="xs:int" />
            <xs:element name="article" type="xs:string" />
            <xs:element name="name" type="xs:string" />
            <xs:element name="qty" type="xs:decimal" />
            <xs:element name="upc" type="xs:string" minOccurs="0" />
            <xs:element name="lot" type="xs:string" minOccurs="0" /> <!-- Добавить поле для возможности видеть остатки в разрезе партии -->
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Notification">
        <xs:annotation>
            <xs:documentation>Базовй класс для уведомлений</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="guid" type="xs:string" minOccurs="0" />
            <xs:element name="orderNo" type="xs:string" />
            <xs:element name="orderDate" type="xs:dateTime" />
            <xs:element name="contrCode" type="xs:string" minOccurs="0" />
            <xs:element name="contrName" type="xs:string" minOccurs="0" />
            <xs:element name="contrAddress" type="xs:string" minOccurs="0" />
            <xs:element name="licencePlate" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>номерной знак</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="driver" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>водитель</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="actualArrivalTime" type="xs:dateTime" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>фактическое время прибытия машины</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="actualDeliveryTime" type="xs:dateTime" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>фактическое время отгрузки</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="line" type="st:NotificationLine" minOccurs="1" maxOccurs="unbounded" />

        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="NotificationLine">
        <xs:annotation>
            <xs:documentation>Уведомление о подтверждении поставки</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="lineNumber" type="xs:int" />
            <xs:element name="article" type="xs:string" />
            <xs:element name="name" type="xs:string" minOccurs="0" />
            <xs:element name="qty" type="xs:decimal" />
            <xs:element name="category" type="xs:string" minOccurs="0" />
            <xs:element name="mark" type="xs:string" minOccurs="0" />
            <xs:element name="mark2" type="xs:string" minOccurs="0" />
            <xs:element name="mark3" type="xs:string" minOccurs="0" />
            <xs:element name="lot" type="xs:string" minOccurs="0" /> <!-- ГТД при приёмке пива и слабоалкогольной продукции, либо номер вет. справки при приёмке по меркурию товаров -->
            <xs:element name="comment" type="xs:string" minOccurs="0" />
            <xs:element name="sn" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>cерийный номер</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="expirationDate" type="xs:date" minOccurs="0" /> <!-- выяснить, берётся ли эта информация с упаковки товара или от клиента? -->
            <xs:element name="productionDate" type="xs:date" minOccurs="0" /> <!-- выяснить, берётся ли эта информация с упаковки товара или от клиента? -->
        </xs:sequence>
    </xs:complexType> <!-- Желательно реализовать возможность повторного запроса уведомления -->

    <xs:complexType name="NotificationTest">
        <xs:complexContent>
            <xs:extension base="st:Notification">
                <xs:sequence>
                    <xs:element name="lines" type="st:NotificationLine" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="NotificationLineTest">
        <xs:complexContent>
            <xs:extension base="st:NotificationLine" />
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="upcList">
        <xs:sequence>
            <xs:element name="upcAlter" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Confirmation">
        <xs:annotation>
            <xs:documentation>Квитирование поступления файлов в обработку</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="status">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="SUCCESS|ERROR" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="info" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Текст ошибки или любая дополнительная информация</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== gem15/notification/src/main/resources/xml/st_sample.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<!--<Shell xmlns="http://www.severtrans.com" 
    xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" 
    xsi:schemaLocation="http://www.severtrans.com severtrans.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
-->
<Shell xmlns="http://www.severtrans.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.severtrans.com severtrans.xsd">
    <customerID>-2758</customerID>
    <skuList>
        <sku>
            <article>string</article>
            <name>string</name>
        </sku>
        <sku>
            <article>string</article>
            <name>string</name>
        </sku>
        <sku>
            <article>string</article>
            <name>string</name>
        </sku>
    </skuList>
    <partStockRq>
        <ts>2015-03-08T18:23:56.11</ts>
    </partStockRq>
    <partStockRs>
        <ts>1987-03-07T15:49:21.13</ts>
        <line>
            <lineNumber>-4660</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>1659850.2349058</qty>
        </line>
        <line>
            <lineNumber>-3106</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>-4161979.7650942</qty>
        </line>
        <line>
            <lineNumber>-172</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>3328250.2349058</qty>
        </line>
        <line>
            <lineNumber>8</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>-1141099.7650942</qty>
        </line>
        <line>
            <lineNumber>866</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>-2265029.7650942</qty>
        </line>
    </partStockRs>
    <order>
        <orderType>Отгрузка</orderType>
        <orderNo>string</orderNo>
        <orderDate>1975-11-02T17:52:43.44</orderDate>
        <plannedDate>1979-11-21T00:02:55.34</plannedDate>
        <contrCode>string</contrCode>
        <contrName>string</contrName>
        <contrAddress>string</contrAddress>
        <licencePlate>string</licencePlate>
        <driver>string</driver>
        <comment>string</comment>
        <orderLine>
            <lineNumber>3139</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>4576870.2349058</qty>
        </orderLine>
        <orderLine>
            <lineNumber>1503</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>-1495009.7650942</qty>
        </orderLine>
        <orderLine>
            <lineNumber>1425</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>1854440.2349058</qty>
        </orderLine>
    </order>
    <pickOrder>
        <guid>string</guid>
        <orderNo>string</orderNo>
        <orderDate>2008-04-02T16:11:17.17</orderDate>
        <plannedDate>1979-04-15T02:33:06.89</plannedDate>
        <contrAddress>string</contrAddress>
        <licencePlate>string</licencePlate>
        <driver>string</driver>
        <actualArrivalTime>1999-02-25T10:43:55.14</actualArrivalTime>
        <actualDeliveryTime>1973-06-17T00:25:23.50</actualDeliveryTime>
        <pickLine>
            <lineNumber>349</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>-2298679.7650942</qty>
        </pickLine>
    </pickOrder>
    <shipmentNotif>
        <guid>string</guid>
        <orderNo>string</orderNo>
        <orderDate>1993-05-01T20:07:47.92</orderDate>
        <plannedDate>1976-09-11T01:19:15.15</plannedDate>
        <contrName>string</contrName>
        <licencePlate>string</licencePlate>
        <driver>string</driver>
        <actualArrivalTime>1987-06-01T13:05:20.88</actualArrivalTime>
        <actualDeliveryTime>2009-03-09T19:42:59.16</actualDeliveryTime>
        <orderLine>
            <lineNumber>-160</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>2633090.2349058</qty>
        </orderLine>
        <orderLine>
            <lineNumber>-3961</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>-4681949.7650942</qty>
        </orderLine>
        <orderLine>
            <lineNumber>-491</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>779690.234905804</qty>
        </orderLine>
    </shipmentNotif>
    <deliveryNotif>
        <guid>string</guid>
        <orderNo>string</orderNo>
        <orderDate>1989-03-10T01:56:40.90</orderDate>
        <plannedDate>2002-12-02T14:33:19.27</plannedDate>
        <licencePlate>string</licencePlate>
        <driver>string</driver>
        <actualArrivalTime>2007-12-17T23:41:31.27</actualArrivalTime>
        <actualDeliveryTime>1979-08-07T09:44:32.27</actualDeliveryTime>
        <orderLine>
            <lineNumber>3980</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>-1348049.7650942</qty>
        </orderLine>
        <orderLine>
            <lineNumber>1285</lineNumber>
            <article>string</article>
            <name>string</name>
            <qty>-2440229.7650942</qty>
        </orderLine>
    </deliveryNotif>
</Shell>
